<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Jellyfin.Plugin.JellyTTV</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.JellyTTV</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.*" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="10.*" ExcludeAssets="runtime" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\**\*" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="icon-512.png" />
  </ItemGroup>

</Project>
