"""Cached proxying of Twitch profile images and live previews.

The dashboard renders a thumbnail *and* an avatar per channel and refetches every
30s, so the naive "fetch from Twitch's CDN on every request" approach both hit
Twitch hard and tripped our own per-IP rate limit, which the browser then
rendered as broken images.

Two rules matter here:

* Cache aggressively. Avatars change once in a blue moon; live previews are only
  regenerated by Twitch every minute or so.
* Never lie about a failure. The previous code answered a failed avatar fetch
  with a 1x1 transparent PNG and a 200, which is exactly why the UI showed blank
  circles with nothing in the logs to explain them. A stale-but-real image is
  fine; a placeholder must be visibly a placeholder.
"""

from __future__ import annotations

import html
import time
from dataclasses import dataclass

import httpx

from app.logging_conf import get_logger
from app.services import http as shared_http
from app.services.http import UPSTREAM_HEADERS

log = get_logger(__name__)

AVATAR_TTL = 6 * 60 * 60.0
PREVIEW_TTL = 60.0
# How long a cached image may still be served after its TTL when upstream is
# failing. A slightly stale preview beats a hole in the page.
STALE_GRACE = 30 * 60.0

_MAX_ENTRIES = 512


@dataclass(slots=True)
class CachedImage:
    content: bytes
    content_type: str
    fetched_at: float
    url: str
    status: int = 200


_cache: dict[str, CachedImage] = {}
# Last failure per cache key, surfaced by diagnostics so blank artwork is
# explainable without turning on debug logging.
_failures: dict[str, tuple[float, str, int]] = {}


def _evict_if_needed() -> None:
    if len(_cache) <= _MAX_ENTRIES:
        return
    oldest = sorted(_cache.items(), key=lambda kv: kv[1].fetched_at)
    for key, _ in oldest[: len(_cache) - _MAX_ENTRIES]:
        _cache.pop(key, None)


async def _fetch(url: str) -> tuple[bytes, str] | None:
    try:
        response = await shared_http.get_client().get(
            url, headers=UPSTREAM_HEADERS, timeout=shared_http.IMAGE_TIMEOUT
        )
    except httpx.HTTPError as exc:
        _failures[url] = (time.time(), str(exc), 0)
        log.warning("image fetch failed", url=url, error=str(exc))
        return None

    if response.status_code != 200:
        _failures[url] = (time.time(), f"HTTP {response.status_code}", response.status_code)
        log.warning("image fetch returned an error", url=url, status=response.status_code)
        return None

    _failures.pop(url, None)
    return response.content, response.headers.get("content-type", "image/jpeg")


async def get_image(key: str, url: str | None, *, ttl: float) -> CachedImage | None:
    """Return a cached or freshly fetched image, or None if unavailable."""
    if not url:
        return None

    now = time.time()
    entry = _cache.get(key)
    if entry is not None and entry.url == url and now - entry.fetched_at < ttl:
        return entry

    fetched = await _fetch(url)
    if fetched is None:
        # Serve stale rather than nothing: a preview that is a minute old is far
        # better than a card with a hole in it.
        if entry is not None and now - entry.fetched_at < ttl + STALE_GRACE:
            return entry
        return None

    content, content_type = fetched
    entry = CachedImage(content=content, content_type=content_type, fetched_at=now, url=url)
    _cache[key] = entry
    _evict_if_needed()
    return entry


def placeholder_avatar(name: str) -> tuple[bytes, str]:
    """A visible initial-letter avatar, so a missing image looks intentional."""
    initial = html.escape((name or "?").strip()[:1].upper() or "?")
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">'
        '<rect width="64" height="64" rx="32" fill="#2e3345"/>'
        '<text x="32" y="41" font-family="system-ui,sans-serif" font-size="28" '
        'font-weight="600" fill="#9aa1b4" text-anchor="middle">'
        f"{initial}</text></svg>"
    )
    return svg.encode("utf-8"), "image/svg+xml"


def placeholder_preview(name: str) -> tuple[bytes, str]:
    """A 16:9 placeholder card for a missing live preview."""
    label = html.escape((name or "").strip()[:24])
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 360" width="640" height="360">'
        '<rect width="640" height="360" fill="#171a24"/>'
        '<circle cx="320" cy="164" r="34" fill="none" stroke="#3a405480" stroke-width="6"/>'
        '<circle cx="320" cy="164" r="10" fill="#6b7285"/>'
        '<text x="320" y="248" font-family="system-ui,sans-serif" font-size="22" '
        'fill="#6b7285" text-anchor="middle">'
        f"{label}</text></svg>"
    )
    return svg.encode("utf-8"), "image/svg+xml"


def failure_report() -> dict[str, dict]:
    """Recent image fetch failures, keyed by url, for /api/diagnostics."""
    now = time.time()
    return {
        url: {"age_s": round(now - at, 1), "error": error, "status": status}
        for url, (at, error, status) in _failures.items()
    }


def reset() -> None:
    _cache.clear()
    _failures.clear()
